### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by arejula27** [cliffniff/media-controls#17] opened 2021-09-14 16:13 UTC
Since the last update i get an error while installing from gnome extensions

**Comment by mBilG** [comment] 2021-09-14 16:29
Same.

Workaround:
Remove the old version.
Install new one.
Log out and log in.
Enable extension.

**Comment by cliffniff** [comment] 2021-09-14 21:19
Since the issue is fixed I will close this.

**Closed by cliffniff** 2021-09-14 21:19 UTC
