### ISSUE TITLE
Clicking on extension is switching through tabs

### ISSUE THREAD

**Issue by vicky-nike** [cliffniff/media-controls#54] opened 2022-01-26 13:36 UTC
https://user-images.githubusercontent.com/40816229/151171829-4889e3eb-c3b3-45ed-bbe1-dbb8e27eca92.mp4

Gnome version: 41.2

Thanks for this great extension, made things easy for me.

**Comment by ChrisLauinger77** [comment] 2023-10-06 06:31
Duplicate of #41 ? Does it also happen when you disable all other running extensions ?
What other extensions are active when this happens ?

**Closed** 2023-10-06 17:49 UTC
Labels: duplicate, invalid
